@startuml Norgespris Status State Machine

[*] --> Initiated : User creates Norgespris contract for meteringpoint

Initiated --> Activated : After 14 days [Contract locked, cannot be cancelled]
Initiated --> Cancelled : User cancels [Within 14 days]
Initiated : API: "active"; Cancellable until 14 days from creation, even past end_date (Dec 31)

Activated --> Expired : Year-end (Dec 31) or immediately if past end_date
Activated : API: "active" if within end_date; Locked (non-revocable)

Expired --> [*] : End
Expired : API: "inactive"

Cancelled --> Initiated : User activates Norgespris again.
Cancelled --> [*] : End
Cancelled : API: "cancelled"

@enduml
