openapi: 3.1.1
info:
  title: Contracts JSON:API
  description: |
    API for managing contract information in the Elhub system.
    Contracts represent agreements on metering points in the Elhub system and is used to represent a variety of different relationships
    that can exist on a metering point. Norgespris is a type of contract in the Elhub information model. Set the server URL to match your environment.
  version: 0.0.1
  contact:
    name: team-wow
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
security:
  - bearerAuth: []
servers:
  - url: http://localhost:8080/v1
    description: Local test server
  - url: https://market-processes-contracts-service-{environment}.elhub.cloud/v1
    description: Test server
    variables:
      environment:
        default: test13
        enum:
          - test9
          - test11
          - test13
paths:
  /contracts:
    get:
      summary: Get all contracts
      description: |
        Get all contracts which you (as a market party or end user) are entitled to view.
        In almost all cases, this means you must have a valid contract on the metering point in order to retrieve information about it.
      operationId: getContracts
      parameters:
        - name: filter[contractType]
          in: query
          description: Filter by contract type. This is used to retrieve all records of a specific type; e.g., all contracts of type Norgespris.
          required: false
          schema:
            type: string
            enum: [Norgespris, BalanceSupplyContract, GridAccessContract, ThirdPartyAccessContract]
        - name: filter[meteringPointId]
          in: query
          description: Filter list by metering point IDs. This is used to retrieve records based on the metering point ID.
          required: false
          schema:
            type: array
            items:
              type: string
        - name: filter[updatedAt][gt]
          in: query
          description: Filter contracts updated after this timestamp (RFC 3339)
          required: false
          schema:
            type: string
            format: date-time
        - name: filter[updatedAt][lt]
          in: query
          description: Filter contracts updated before this timestamp (RFC 3339)
          required: false
          schema:
            type: string
            format: date-time
      responses:
        "200":
          description: Successfully get contracts
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/ContractResponse"
        "400":
          description: Bad Request - When the request is invalid
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a contract
      description: Create one or more contracts linked to meteringPointId(s).
      operationId: createContracts
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: "#/components/schemas/ContractRequest"
            example:
              data:
                - type: contract
                  attributes:
                    contractType: Norgespris
                    status: Activated
                    validFrom: "2026-01-01"
                    validTo: "2026-12-31"
                  relationships:
                    createdBy:
                      data:
                        type: Party
                        id: "GLN1234567890123"
                    meteringPoint:
                      data:
                        type: MeteringPoint
                        id: "MP123456789"
      responses:
        "201":
          description: Successfully created contract
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/ContractResponse"
        "400":
          description: Bad Request - When the request is invalid
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/Error"
    patch:
      summary: Update contracts
      description: Update a set of contracts.
      operationId: updateContracts
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: "#/components/schemas/ContractRequest"
            example:
              data:
                - type: contract
                  attributes:
                    contractType: Norgespris
                    status: Activated
                    validFrom: "2026-01-01"
                    validTo: "2026-12-31"
                  relationships:
                    createdBy:
                      data:
                        type: Party
                        id: "GLN1234567890123"
                    meteringPoint:
                      data:
                        type: MeteringPoint
                        id: "MP123456789"
      responses:
        "200":
          description: Successfully updated contract
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/ContractResponse"
        "400":
          description: Bad Request - When the request is invalid
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/Error"
  /contracts/{contractId}:
    get:
      summary: Get a single contract by ID
      description: Get a single contract entity identified by ID.
      operationId: getContractById
      parameters:
        - name: contractId
          in: path
          description: The ID of the contract to retrieve.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully get contract by ID
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/ContractResponse"
        "400":
          description: Bad Request - When the request is invalid
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/Error"
    patch:
      summary: Update a contract by ID
      description: Update a contract entity identified by ID.
      operationId: patchContractById
      parameters:
        - name: contractId
          in: path
          description: The ID of the contract to update.
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: "#/components/schemas/ContractRequest"
      responses:
        "200":
          description: Successfully updated contract
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/ContractResponse"
        "400":
          description: Bad Request - When the request is invalid
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/Error"
  /contracts/{contractId}/status:
    get:
      summary: Get contract status history
      description: Get the status history for a specific contract, ordered by creation date (most recent first).
      operationId: getContractStatusHistory
      parameters:
        - name: contractId
          in: path
          description: The ID of the contract for which the status history will be retrieved.
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Successfully retrieved contract status history
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/ContractStatusResponse"
        "400":
          description: Bad Request - When the request is invalid
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Contract not found
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    ContractResponse:
      allOf:
        - $ref: "./schemas/norgespris-contract-response.schema.json#/definitions/response"
    ContractRequest:
      allOf:
        - $ref: "./schemas/norgespris-contract-request.schema.json#/definitions/request"
    Contract:
      allOf:
        - $ref: "./schemas/norgespris-contract.schema.json#/definitions/contract"
    ContractAttributes:
      allOf:
        - $ref: "./schemas/norgespris-contract-attributes.schema.json#/definitions/attributes"
    ContractStatusResponse:
      allOf:
        - $ref: "./schemas/contract-status-response.schema.json#/definitions/response"
    ContractStatus:
      allOf:
        - $ref: "./schemas/contract-status.schema.json#/definitions/contract-status"
    ContractStatusAttributes:
      allOf:
        - $ref: "./schemas/contract-status-attributes.schema.json#/definitions/attributes"
    ContractStatusRelationships:
      allOf:
        - $ref: "./schemas/contract-status-relationships.schema.json#/definitions/relationships"
    Meta:
      allOf:
        - $ref: "./schemas/norgespris-contract-meta.schema.json#/definitions/meta"
    Error:
      allOf:
        - $ref: "./schemas/json-api-error.schema.json#/definitions/error"
    Relationships:
      allOf:
        - $ref: "./schemas/norgespris-contract-relationships.schema.json#/definitions/relationships"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
